// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3Ez8MH8bRnHK2QT3pXZ0yzlP2ojQQGsE',
    appId: '1:571953732019:web:0695a950fa8d6d4a2793c6',
    messagingSenderId: '571953732019',
    projectId: 'django-notifications-40ebc',
    authDomain: 'django-notifications-40ebc.firebaseapp.com',
    storageBucket: 'django-notifications-40ebc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzwenuTqCTeIO0z2nPQCw6lnlfQ7g8vSs',
    appId: '1:571953732019:android:e49a721af984b98d2793c6',
    messagingSenderId: '571953732019',
    projectId: 'django-notifications-40ebc',
    storageBucket: 'django-notifications-40ebc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACVjQyD5bd9qkMz7TBDuqeHtwzNIzsPng',
    appId: '1:571953732019:ios:4c6b1f56c29bff4d2793c6',
    messagingSenderId: '571953732019',
    projectId: 'django-notifications-40ebc',
    storageBucket: 'django-notifications-40ebc.appspot.com',
    iosBundleId: 'com.example.registrationApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACVjQyD5bd9qkMz7TBDuqeHtwzNIzsPng',
    appId: '1:571953732019:ios:4c6b1f56c29bff4d2793c6',
    messagingSenderId: '571953732019',
    projectId: 'django-notifications-40ebc',
    storageBucket: 'django-notifications-40ebc.appspot.com',
    iosBundleId: 'com.example.registrationApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD3Ez8MH8bRnHK2QT3pXZ0yzlP2ojQQGsE',
    appId: '1:571953732019:web:2e403d6dc02518ff2793c6',
    messagingSenderId: '571953732019',
    projectId: 'django-notifications-40ebc',
    authDomain: 'django-notifications-40ebc.firebaseapp.com',
    storageBucket: 'django-notifications-40ebc.appspot.com',
  );
}
